### PR TITLE
Update docs and image to match new index name pattern

### PR DESCRIPTION
**Pull request by ruflin**
As in https://github.com/elastic/packetbeat/pull/186 the index pattern was updated, the screenshot and additional parts of the documentation had to be updated.

### CODE REVIEW

**Comment by tsg** [comment]
The screenshot it is a bit big. It's good to have the images max 800px in the docs. Here is how it currently looks:

screen shot 2015-09-04 at 09 46 39

**Comment by tsg** [comment]
We should do the same for the Topbeat guide.

**Comment by ruflin** [comment]
Image exchanged. I will also do it for Topbeat: https://github.com/elastic/topbeat/issues/25

**Comment by tsg** [comment]
Thanks!

**Pull request merged**
