### PR TITLE
Update CONTRIBUTING.md & Update Travis file to build under Go 1.5

### PR DESCRIPTION
**Pull request by emirozer**
I am not sure if this is necessary or not, just that a fresh clone won't run make if libpcap is missing(naturally as libpcap being the backbone of the app :) ).

Also updated the travis file to target Go 1.5 from now on

### CODE REVIEW

**Comment by emirozer** [comment]
Oh.. I guess on Go 1.5 mongodb has issues.. 

Here is the Travis build : https://travis-ci.org/elastic/packetbeat/builds/76619151
Here is an example of another trouble: https://groups.google.com/forum/#!msg/golang-nuts/wRQwpRJvDHU/W2Yqys4yG1wJ

**Comment by tsg** [comment]
It passed now. Not sure why, but that last mongodb test seems to be flaky (also with go 1.4). 

Thanks for the PR, we want to release the beta3 in 1-2 weeks and we're not sure yet if we want to base it on go 1.4 or 1.5. We'll merge this when we switch to 1.5.

**Comment by ruflin** [comment]
@emirozer We updated to 1.5 in the mean time. I would still like to get your change to CONTRIBUTING.md into the repo. Can you merge in master and push again?

**Comment by emirozer** [comment]
@ruflin thank you :)

**Comment by ruflin** [comment]
Merged, thx.

**Pull request merged**
