### PR TITLE
Use [packetbeat-]YYYY.MM.DD

### PR DESCRIPTION
**Pull request by fedelemantuano**
Use `[packetbeat-]YYYY.MM.DD` to better manage query and dashboard in Elasticsearch.

With this pull request must change the dashboard.

### CODE REVIEW

**Comment by tsg** [comment]
Hi @fedelemantuano, thanks for the pull request. When you say this helps to better manage the queries what do you refer exactly to? I asked the Kibana folks and from what I understand the only advantage would be that it avoids false negative matches if you have other indexes starting with 'packetbeat-'. Was that your case?

**Comment by fedelemantuano** [comment]
With `packetbeat-` ELK use all indexes, while with `[packetbeat-]YYYY.MM.DD` uses only precise days.

**Comment by tsg** [comment]
Ah, you are right, it is better. Can you sign the CLA please? We also need to update the screenshot there.

**Comment by fedelemantuano** [comment]
This is my signed CLA:
individual contributor license agreement - signed-0
individual contributor license agreement - signed-1

**Comment by ruflin** [comment]
@fedelemantuano To make this work, "Use event times to create index names" must also be activated. I will merge the pull request and adjust the documentation with the above and the screenshot.

**Pull request merged**
