### PR TITLE
Add saltstack deploy method

### PR DESCRIPTION
**Pull request by joshboon**
This pull request is for deploying the packetbeat agent automatically using saltstack. http://www.saltstack.com/ I use it in my environment and thought I would contribute it here to help speed deployment for other folks who also use it. Feel free to ask any questions or ping me for basic support.

### CODE REVIEW

**Comment by mr337** [comment]
Thanks for doing a PR, we just found this and looking to deploy as a test.

**Comment by tsg** [comment]
@mr337 note that it's a bit old and we change the configuration file from toml to yaml in the mean time. But it shouldn't be too hard to adapt.

**Comment by ruflin** [comment]
@joshboon Packetbeat has now a .yml file as configuration. Could you update the pull request with the new .yml config file? It can be found here: https://github.com/elastic/packetbeat/blob/master/etc/packetbeat.yml

**Comment by joshboon** [comment]
I've updated the pull request to yaml and move the config to pillars to allow easier config for more advanced deployments. I've not used packetbeat in awhile but the initial salt deploy went OK so I don't expect any issues.

**Comment by ruflin** [comment]
@joshboon Thanks for the contribution. We will probably move it to a separate repository at a later stage where we have it together with other deploy scripts.

**Comment by tsg** [comment]
@joshboon Hi, we were discussing where the saltstack files should live and we feel like the best place for them would be in a public github repo under your user name. This is because we don't have the knowledge/resources to help users that try to use them, on the other hand the scripts can still be useful for lots of users, so we can point folks to them. This is what we do for chef and puppet for now, for example. What do you think?

**Pull request merged**
