### PR TITLE
Centos6 Docker

### PR DESCRIPTION
**Pull request by islamgulov**
Hello.

I failed to run packetbeat builded on ubuntu 14.04 at Amazon AMI instance. So I used this Dockerfile to build packetbeat on centos 6.

### CODE REVIEW

**Comment by eperry** [comment]
I use cloud9  for my IDE and build env,   I think they also use docker now
too.  I highly advise you checking it out as it makes occasional developing
and re-compiles easy

https://ide.c9.io/eperry/packetbeat


On Thu, Feb 19, 2015 at 5:40 PM, Ilgiz Islamgulov <notifications@github.com>
wrote:

> Hello.
>
> I failed to run packetbeat builded on ubuntu 14.04 at Amazon AMI instance.
> So I used this Dockerfile to build packetbeat on centos 6.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/packetbeat/packetbeat/pull/95
> Commit Summary
>
>    - fix tests on python 2.6
>    - Centos6 Dockerfile
>
> File Changes
>
>    - *M* Dockerfile
>    <https://github.com/packetbeat/packetbeat/pull/95/files#diff-0> (25)
>    - *M* tests/pbtests/packetbeat.py
>    <https://github.com/packetbeat/packetbeat/pull/95/files#diff-1> (2)
>
> Patch Links:
>
>    - https://github.com/packetbeat/packetbeat/pull/95.patch
>    - https://github.com/packetbeat/packetbeat/pull/95.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/packetbeat/packetbeat/pull/95>.
>



-- 
Sincerely

Edward Perry

**Comment by tsg** [comment]
Thanks for the pull request. I'll check it when we get ready for the next release.

**Comment by ruflin** [comment]
@islamgulov Does this issue still exist with the newest version of packetbeat?

**Comment by tsg** [comment]
Closing this one as we're preparing moving repos around and we prefer runtime Dockerfiles to live in separate repos. Sorry for closing after such a long time.

**Pull request closed without merging**
