### PR TITLE
Remove build directory

### PR DESCRIPTION
**Pull request by tsg**
This just deletes the `build/` folder from the repository. It was committed by mistake, it's contents are generated when building the packages.

Thanks to @darxriggs for reporting it [here](https://github.com/elastic/packetbeat/commit/cb72d3a3482d5c5a085a5c410d8f358e42487d05#commitcomment-13264801).

### CODE REVIEW

**Comment by darxriggs** [comment]
I would also add it to `.gitignore` and to the `clean` target in the Makefile.
I am not sure how you "maintain" the directory creation itself as the `install_cfg` target does only copy files to the `build` directory but does not create it.

**Comment by tsg** [comment]
Added `build/` to the `.gitignore`. The directory is created from `beats-packer`, and actually it's normally not in the repository directory but put under `/build/` in a docker container. When I committed it by mistake I must have done manual testing of it.

**Comment by ruflin** [comment]
@tsg Looks good to me. Can you merge in again master as there is a conflict?

**Comment by tsg** [comment]
Merged master.

**Pull request merged**
