### PR TITLE
Update to most recent libbeat version and shared files

### PR DESCRIPTION
**Pull request by ruflin**

### CODE REVIEW

**Comment by tsg** [comment]
I fixed the system tests in #376, I recommend opening it again :-).

**Comment by tsg** [comment]
Or better, wait until we have all changes in libbeat.

**Comment by andrewkroh** [comment]
The file `tests/system/templates/packetbeat.yml.j2` has an `enabled: true` that should be removed now.

**Comment by ruflin** [comment]
Oh, I also just fixed it :-( Good we found the same fix. Reading e-mails first in the morning would help :-) Will open new pull requests for all repos.

**Comment by ruflin** [comment]
@andrewkroh Fixing the tests I realised the enabled flag was very convenient during testing as it allowed to enable outputs through a flag. Also for manual testing it is quite convenient. Not 100% sure anymore if removal was a good idea for the outputs.

**Pull request closed without merging**
