### PR TITLE
use Python virtualenv also for main Makefile

### PR DESCRIPTION
**Pull request by darxriggs**
* Makefile and tests/Makefile run Python scripts
* so have a global virtualenv to make sure all required Python modules are available

### CODE REVIEW

**Comment by ruflin** [comment]
@darxriggs Python is only required for the integration tests. So we don't need to have it available globally. The question is probably if the two Makefiles should be reduced to one.

**Comment by darxriggs** [comment]
Python is also required to run to `gen` target in the main Makefile (see my change).

Without this change, running `make gen` with a clean Python installation fails because the `yaml` module cannot be found.

**Comment by ruflin** [comment]
Ah, I see, it is to generate the docs. @monicasarbu You are probably the best to have a look at this.

**Comment by monicasarbu** [comment]
Merged here: https://github.com/elastic/packetbeat/pull/248 Thank you @darxriggs for your contribution.

**Pull request merged**
