### PR TITLE
IPv4 defragmentation support

### PR DESCRIPTION
**Pull request by urso**
DO NOT MERGE

an experiment on ip defragmentation in conjunction with DecodingLayerParser... they don't fit well...

### CODE REVIEW

**Comment by ruflin** [comment]
@urso Build is broken :-(

**Comment by urso** [comment]
No worries, working on it. Need to add some more PRs to google/gopacket. Very early preview.

**Comment by urso** [comment]
Builds now, but requires some testing

**Comment by tsg** [comment]
Closing this one for now after discussing it briefly with @urso.

**Pull request closed without merging**
